version: "3"

services:
  frontend:
    container_name: frontend
    ports:
      - 3000:3000
    build: ./
    volumes:
      - "./:/app"
      - "/app/node_modules"
      - "/app/.next"
    # command: 
    #  sh -c "npm run build && chown -R $USER:$USER /app/.next/ && npm run start"